[package]
name = "moveit"
version = "0.1.4"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["raw_value"] }
clap = { version = "4.5.32" }
walkdir = "2.3"
chrono = "0.4.40"