[package]
name = "moveit"
version = "0.1.2"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = { version = "1.0.133", features = ["raw_value"] }
clap = { version = "4.5.21" }
walkdir = "2.3"
chrono = "0.4"