[package]
name = "moveit"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["raw_value"] }
clap ={ version = "4.5.20" }
walkdir = "2.3"
chrono = "0.4"