[package]
name = "moveit"
version = "0.1.3"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138", features = ["raw_value"] }
clap = { version = "4.5.30" }
walkdir = "2.3"
chrono = "0.4.39"